BoardGameAuction/Models/ItemViewModel.cs
namespace BoardGameAuction.Models
{
	public class ItemViewModel : Item
	{
		public string LinkUrl { get; set; }
		public int ExpansionsCount { get; set; }
	}
}

BoardGameAuction/Controllers/LotController.cs
using BoardGameAuction.Models;
using BoardGameAuction.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Polly.CircuitBreaker;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BoardGameAuction.Controllers
{
	[Authorize]
	[Route("[controller]")]
    public class LotController : Controller
    {
		private readonly ILogger<LotController> _logger;
		private readonly AppSettings _appSettings;
		private readonly ILotService _service;
		private readonly IItemService _itemService;
		private readonly IAuctionService _auctionService;

		public LotController(ILogger<LotController> logger, IOptions<AppSettings> appSettings, ILotService service, IItemService itemService, IAuctionService auctionService)
		{
			_logger = logger;
			_appSettings = appSettings.Value;
			_service = service;
			_itemService = itemService;
			_auctionService = auctionService;
		}

		public async Task<IActionResult> Index(int id)
        {
			var bearer = User.FindFirst("Access_Token").Value;
			try
			{
				var lot = await _service.Get(id, bearer);
				var auction = await _auctionService.Get(bearer);
				ViewData.Add("allowEdits", auction.Status == Models.Types.AuctionStatus.NotStarted);
				return View(lot);
			}
			catch (BrokenCircuitException)
			{
				ModelState.AddModelError(string.Empty, "Lot Service inoperative");
				return View();
			}
		}

		[Authorize(Policy = "IsSeller")]
		[Route("{id}/item/add")]
		public async Task<IActionResult> AddItem(int id)
		{
			if (id != 0)
			{
				var bearer = User.FindFirst("Access_Token").Value;
				var lot = await _service.Get(id, bearer);

				if (lot?.Seller == null || lot.Seller?.Id != int.Parse(User.FindFirst(c => c.Type == "nameid").Value))
				{
					return RedirectToAction("Index", "Home");
				}

				var model = new LotAddViewModel { 
					LotId = id,
					StartPrice = lot.StartPrice,
					EndPrice = lot.EndPrice,
					Items = lot.Items.Select(p => new ProductViewModel(p)).ToList()
				};
				return View(model);
			}

			return View(new LotAddViewModel { LotId = id });
		}

		[HttpPost]
		[RequestFormLimits(ValueCountLimit = 7500)]
		[Authorize(Policy = "IsSeller")]
		[Route("{id}/item/add")]
		public async Task<IActionResult> AddItem(LotAddViewModel model)
		{
			if (model.LotId == 0 && model.Items?.Count == 0)
			{
				ModelState.AddModelError(string.Empty, "Nothing was selected");
			}

			if (ModelState.IsValid == false)
			{
				return View(model);
			}

			var bearer = User.FindFirst("Access_Token").Value;

			// Although the viewmodel is ready for a list, we only implement it
			// as a single selection at present
			Item item = default;
			if (model.Items.Count(x => x.VersionId == x.VersionId) > 0)
			{
				var selectedItemVersion = model.Items.First().Versions.First(v => v.VersionId == model.Items.First().VersionId);
				item = new Item(selectedItemVersion);
				item.Notes = model.Items.First(x => x.Id == 0).Notes;

				foreach (var expansion in model.Items.First().Expansions.Where(e => e.IsChecked))
				{
					ProductViewModel selectedExpansionVersion;
					if (expansion?.Versions.Count > 1)
					{
						selectedExpansionVersion = expansion.Versions.FirstOrDefault(v => v.VersionId == expansion.VersionId);
					}
					else
					{
						selectedExpansionVersion = expansion.Versions.FirstOrDefault();
					}
					if (selectedItemVersion != null)
					{
						item.Expansions.Add(new Expansion(selectedExpansionVersion)
						{
							ItemId = item.Id,
							ProductId = selectedExpansionVersion.Id,
							Notes = expansion.Notes
						});
					}
				}
			}

			try
			{
				if (model.LotId == 0 && item != default)
				{
					var lot = new Lot
					{
						StartPrice = model.StartPrice.Value,
						EndPrice = model.EndPrice.Value,
						Items = new List<Item> { item }
					};
				
					var newLot = await _service.Add(lot, bearer);

					return View("AddConfirmation", newLot);
				} 
				else
				{
					if (item != default)
					{
						await _itemService.Add(model.LotId, item, bearer);
					}

					var lot = await _service.Get(model.LotId, bearer);

					if (lot.StartPrice != model.StartPrice || lot.EndPrice != model.EndPrice)
					{
						lot.StartPrice = model.StartPrice.Value;
						lot.EndPrice = model.EndPrice.Value;
						lot = await _service.Edit(lot, bearer);
					}
					return View("AddConfirmation", lot);
				}
			}
			catch (BrokenCircuitException)
			{
				ModelState.AddModelError(string.Empty, "Lot Service inoperative");
				return View();
			}
			catch (Exception ex)
			{
				return null;
			}
		}

		[HttpPost]
		[Authorize(Policy = "IsSeller")]
		[Route("{id}/delete/{itemId}")]
		public async Task<IActionResult> DeleteItem(int id, int itemId)
		{
			if (id != 0)
			{
				var bearer = User.FindFirst("Access_Token").Value;

				var lot = await _service.Get(id, bearer);

				if (lot?.Seller == null || lot.Seller?.Id != int.Parse(User.FindFirst(c => c.Type == "nameid").Value))
				{
					return RedirectToAction("Index", "Home");
				}

				if (lot.Items.Count <= 1)
				{
					ModelState.AddModelError(string.Empty, "A lot cannot be empty. Add an item before deleting the last one");
					return View("EditItem", lot);
				}

				await _itemService.Delete(itemId, id, bearer);

				return RedirectToAction("Index", new { id = id });
			}

			return View(new LotAddViewModel { LotId = id });
		}

		[HttpPost]
		[Route("{id}/makeactive")]
		public async Task<IActionResult> MakeActive(int id)
		{
			try
			{
				var bearer = User.FindFirst("Access_Token").Value;
				if (ModelState.IsValid == false)
				{
					return new EmptyResult();
				}

				var auctionId = int.Parse(User.FindFirst("auction").Value);
				await _service.MakeActive(id, auctionId, bearer);
				return new EmptyResult();
			}
			catch (BrokenCircuitException)
			{
				ModelState.AddModelError(string.Empty, "Lot Service inoperative");
				return View();
			}
			catch (Exception ex)
			{
				ModelState.AddModelError(string.Empty, ex.Message);
				return View();
			}
		}

		[HttpPost]
		[Route("sell")]
		public async Task<IActionResult> Sell(Lot model)
		{
			try
			{
				var bearer = User.FindFirst("Access_Token").Value;
				if (ModelState.IsValid == false)
				{
					// This is a rare-enough event that we can swallow the
					// cost of getting the model to avoid passing a load 
					// of hidden controls to the view
					var lot = await _service.Get(model.Id, bearer);
					lot.SalePrice = model.SalePrice;
					return PartialView("_Lot", lot);
				}

				var auctionId = int.Parse(User.FindFirst("auction").Value);
				await _service.Sell(model.Id, auctionId, model.SalePrice.Value, model.Seller.Id, bearer);
				return new EmptyResult();
			}
			catch (BrokenCircuitException)
			{
				ModelState.AddModelError(string.Empty, "Lot Service inoperative");
				return View();
			}
			catch (Exception ex)
			{
				ModelState.AddModelError(string.Empty, ex.Message);
				return View();
			}
		}

		[HttpGet]
		[Route("{id}/delete")]
		public async Task<IActionResult> Delete(int id)
		{
			try
			{
				var bearer = User.FindFirst("Access_Token").Value;
				var auctionId = User.FindFirst("auction").Value;

				await _service.Delete(int.Parse(auctionId), id, bearer);
				return RedirectToAction("Index", "Auction");
			}
			catch (BrokenCircuitException)
			{
				ModelState.AddModelError(string.Empty, "Lot Service inoperative");
				return View("Index");
			}
			catch (Exception ex)
			{
				ModelState.AddModelError(string.Empty, ex.Message);
				return View("Index");
			}
		}
	}
}

BoardGameAuction/Controllers/SearchController.cs
using BoardGameAuction.Models;
using BoardGameAuction.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Polly.CircuitBreaker;
using System.Linq;
using System.Threading.Tasks;

namespace BoardGameAuction.Controllers
{
	[Route("[controller]")]
	public class SearchController : Controller
    {
        private readonly ILogger<SearchController> _logger;
        private readonly AppSettings _appSettings;
		private readonly ISearchService _service;
		
		public SearchController(ILogger<SearchController> logger, IOptions<AppSettings> appSettings, ISearchService service)
        {
            _logger = logger;
            _appSettings = appSettings.Value;
			_service = service;
        }

		[HttpGet]
		[Route("byname")]
        public async Task<IActionResult> ByName([FromQuery] string query)
        {
			var bearer = User.FindFirst("Access_Token").Value;

			try
			{
				var searchResult = await _service.ByName(query, bearer);

				if (searchResult == null || searchResult.Items.Count == 0)
				{
					ModelState.AddModelError(string.Empty, "No results found");
				}

				return PartialView("_NameSearchResult", searchResult);
			}
			catch (BrokenCircuitException)
			{
				var model = new NameSearchResponse();
				ModelState.AddModelError(string.Empty, "Search Service inoperative");
				return PartialView("_NameSearchResult", model);
			}
		}

		[HttpGet]
		[Route("byid")]
		public async Task<IActionResult> ById(int id)
		{
			if (id == 0)
			{
				ModelState.AddModelError(string.Empty, "No id provided");
				return View(id);
			}

			var bearer = User.FindFirst("Access_Token").Value;
			try
			{
				var searchResult = await _service.ById(new int[] { id }, bearer);
				if (searchResult.Items.Count == 0)
				{
					ModelState.AddModelError(string.Empty, $"No Results for {id}");
				}
				return PartialView("_IdSearchResult", new LotAddViewModel { Items = searchResult.Items.Select(p => new ProductViewModel(p)).ToList() });
			}
			catch (BrokenCircuitException)
			{
				var model = new LotAddViewModel();
				ModelState.AddModelError(string.Empty, "Search Service inoperative");
				return PartialView("_IdSearchResult", model);
			}
		}
	}
}

BoardGameAuction/Views/Shared/Error401.cshtml
@{
    ViewData["Title"] = "401 - Unauthorised";
}

    <div class="text-center mt-5" style="position: relative;">
        <span class="fa-stack fa-9x">
            <i class="fas fa-door-closed fa-stack-2x"></i>
        </span>
        <div class="text-white" style="position: absolute; top: 13%; width: 100%; margin: 0 auto; font-size: 1.5em; font-weight: 700;">Private</div>
        <div class="" style="position: absolute; top: 10%; left: 60%; font-size: 2.5em; font-weight: 700;">401</div>
        <h1 class="mt-5">Unauthorised</h1>
    </div>

BoardGameAuction/Views/Shared/_IdSearchResult.cshtml
@model LotAddViewModel

<span asp-validation-summary="All" />
@{ int itemIndex = 0; }
@foreach (var item in Model.Items)
{
    <input type="hidden" asp-for="@Model.Items[itemIndex].BGGId" />
    <input type="hidden" asp-for="@Model.Items[itemIndex].Name" />
    <input type="hidden" asp-for="@Model.Items[itemIndex].ImageUrl" />
    <input type="hidden" asp-for="@Model.Items[itemIndex].Year" />
    <input type="hidden" asp-for="@Model.Items[itemIndex].Rating" />
    <input type="hidden" asp-for="@Model.Items[itemIndex].Weight" />

    <h4>@item.Name</h4>
    @if (item.Versions.Count == 1) { <h5>Select the version</h5> }
    <div class="product-wrapper">
        @if (item.Versions.Count == 1)
        {
            <div class="rich-select-option-body pl-2">
                <input type="hidden" asp-for="@Model.Items[itemIndex].VersionId" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[0].BGGId" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[0].VersionId" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[0].VersionName" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[0].Name" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[0].ImageUrl" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[0].Year" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[0].Rating" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[0].Weight" />
                <img src="@item.Versions[0].ImageUrl" alt="">@item.Versions[0].VersionName (@item.Versions[0].Year)
            </div>
        }
        else
        {
            <div class="rich-select custom-select">
                <div class="rich-select-dropdown">
                    @{ int versionIndex = 0; }
                    @foreach (var version in item.Versions)
                    {
                        <div class="rich-select-option">
                            <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[versionIndex].BGGId" />
                            <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[versionIndex].Name" />
                            <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[versionIndex].VersionId" />
                            <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[versionIndex].VersionName" />
                            <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[versionIndex].ImageUrl" />
                            <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[versionIndex].Year" />
                            <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[versionIndex].Rating" />
                            <input type="hidden" asp-for="@Model.Items[itemIndex].Versions[versionIndex].Weight" />
                            @Html.RadioButtonFor(x => Model.Items[itemIndex].VersionId, Model.Items[itemIndex].Versions[versionIndex].VersionId, new { @id = $"{itemIndex}_SelectedVersion_{version.VersionId}" })
                            <div class="rich-select-option-body">
                                <label tabindex="-1"><img src="@version.ImageUrl" alt="">@version.VersionName (@version.Year)</label>
                            </div>
                        </div>
                        versionIndex++;
                    }
                </div>
                <input type="checkbox" id="rich-select-dropdown-button" class="rich-select-dropdown-button" />
                <label for="rich-select-dropdown-button"></label>

                <div class="rich-select-options">
                    @{ versionIndex = 0; }
                    @foreach (var version in item.Versions)
                    {
                        <div class="rich-select-option">
                            <div class="rich-select-option-body">
                                <label for="@Html.Raw($"{itemIndex}_SelectedVersion_{version.VersionId}")" tabindex="-1" onclick="document.getElementById('rich-select-dropdown-button').click();">
                                    <img src="@version.ImageUrl" alt=""> @version.VersionName (@version.Year)
                                </label>
                            </div>
                        </div>
                        versionIndex++;
                    }
                </div>
            </div>
        }
    
        <input id="addNote-@item.BGGId" class="addNote" type="checkbox" />
        <label for="addNote-@item.BGGId" class="addNote" unselectable="on">
            <span class="fa-stack">
                <i class="fas fa-sticky-note fa-stack-2x unchecked"></i>
                <i class="fas fa-plus fa-stack-1x fa-inverse unchecked"></i>
                <i class="far fa-sticky-note fa-stack-2x checked"></i>
            </span>
            <span class="addNoteText d-none d-sm-inline-block">Add Note</span>
        </label>
        <textarea class="addNote" asp-for="@Model.Items[itemIndex].Notes"></textarea>
    </div>

    if (item.Expansions.Count > 0)
    {
        int expansionIndex = 0;
        <h5 class="mt-3">Include Expansions?</h5>
        @foreach (var expansion in item.Expansions)
        {
            <div class="form-row resultRow">
                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].BGGId" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Name" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].ImageUrl" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Year" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Rating" />
                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Weight" />

                <div class=" custom-control custom-checkbox">
                    @*<input type="checkbox" class="expansion-checkbox custom-control-input" id="exp-@expansion.BGGId">*@
                    @Html.CheckBoxFor(x => Model.Items[itemIndex].Expansions[expansionIndex].IsChecked, new { @id = $"exp-{Model.Items[itemIndex].Expansions[expansionIndex].BGGId}", @class = "expansion-checkbox custom-control-input" })
                    <label class="custom-control-label" for="exp-@expansion.BGGId">

                        @if (expansion.Versions.Count == 1)
                        {
                            <div class="rich-select-option-body pl-2">
                                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].VersionId" />
                                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[0].BGGId" />
                                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[0].VersionId" />
                                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[0].VersionName" />
                                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[0].Name" />
                                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[0].ImageUrl" />
                                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[0].Year" />
                                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[0].Rating" />
                                <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[0].Weight" />
                                <img src="@expansion.ImageUrl" />@expansion.Name: @expansion.Versions[0].VersionName (@expansion.Versions[0].Year)
                            </div>
                        }
                        else
                        {
                            <div class="rich-select custom-select d-block">
                                <div class="rich-select-dropdown">
                                    @{ int expansionVersionIndex = 0; }
                                    @foreach (var version in expansion.Versions)
                                    {
                                        <div class="rich-select-option">
                                            <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].BGGId" />
                                            <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].Name" />
                                            <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].VersionId" />
                                            <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].VersionName" />
                                            <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].ImageUrl" />
                                            <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].Year" />
                                            <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].Rating" />
                                            <input type="hidden" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].Weight" />
                                            @Html.RadioButtonFor(x => Model.Items[itemIndex].Expansions[expansionIndex].VersionId, Model.Items[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].VersionId, new { @id = $"{itemIndex}_{expansionIndex}_SelectedVersion_{version.VersionId}" })
                                            @*<input type="radio" name="exp-@Model[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].BGGId" id="exp-@Model[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].BGGId-@Model[itemIndex].Expansions[expansionIndex].Versions[expansionVersionIndex].VersionId" @if (expansionVersionIndex == 0) { @Html.Raw(" checked") ; } />*@
                                            <div class="rich-select-option-body">
                                                <label tabindex="-1">
                                                    <img src="@version.ImageUrl" alt="">@expansion.Name: @version.VersionName (@version.Year)
                                                </label>
                                            </div>
                                        </div>
                                        expansionVersionIndex++;
                                    }
                                </div>
                                <input type="checkbox" id="rich-select-dropdown-button-@expansion.BGGId" class="rich-select-dropdown-button" />
                                <label for="rich-select-dropdown-button-@expansion.BGGId"></label>
                                <div class="rich-select-options">
                                    @{ expansionVersionIndex = 0; }
                                    @foreach (var version in expansion.Versions)
                                    {
                                        <div class="rich-select-option">
                                            <div class="rich-select-option-body">
                                                <label for="@Html.Raw($"{itemIndex}_{expansionIndex}_SelectedVersion_{version.VersionId}")" tabindex="-1" onclick="document.getElementById('rich-select-dropdown-button-@expansion.BGGId').click();">
                                                    <img src="@version.ImageUrl" alt="">@expansion.Name: @version.VersionName (@version.Year)
                                                </label>
                                            </div>
                                        </div>
                                        expansionVersionIndex++;
                                    }
                                </div>
                            </div>
                        }
                    </label>

                    <input id="addNote-exp-@expansion.BGGId" class="addNote" type="checkbox" />
                    <label for="addNote-exp-@expansion.BGGId" class="addNote" unselectable="on">
                        <span class="fa-stack">
                            <i class="fas fa-sticky-note fa-stack-2x unchecked"></i>
                            <i class="fas fa-plus fa-stack-1x fa-inverse unchecked"></i>
                            <i class="far fa-sticky-note fa-stack-2x checked"></i>
                        </span>
                        <span class="addNoteText d-none d-sm-inline-block">Add Note</span>
                    </label>
                    <textarea class="addNote" asp-for="@Model.Items[itemIndex].Expansions[expansionIndex].Notes"></textarea>
                </div>
            </div>
            expansionIndex++;
        }
    }
    itemIndex++;
}

BoardGameAuction/Views/Shared/_Item.cshtml
@model Item

@{
    <div>
        <input type="hidden" asp-for="Id" />
        <a asp-action="Index" asp-controller="Lot" asp-route-id="@Model.LotId">
            <img class="lot-image-single" src=@Model.ImageUrl width="150" />
        </a>
        <div class="d-inline-block align-top">
            <span class="rating-icon d-block fa-stack fa-1x mb-3" title="@Html.Raw($"Rated {@Model.Rating} / 10")">
                <i class="fas fa-certificate fa-stack-2x"></i>
                <strong class="pt-1 fa-stack-1x">@Model.Rating</strong>
            </span>
            <span class="weight-icon d-block fa-stack fa-1x mb-3" title="@Html.Raw($"Weight {Model.Weight} / 5")">
                <i class="fas fa-weight-hanging fa-stack-2x"></i>
                <strong class="pt-2 fa-stack-1x"><small>@Model.Weight</small></strong>
            </span>

            @if (Model.Expansions.Count != 0)
            {
                <span class="expansions-icon d-block fa-stack fa-1x mb-1" title="@Html.Raw($"Includes {Model.Expansions.Count} expansions")">
                    <i class="fas fa-stop fa-stack-2x"></i>
                    <strong class="pb-0 fa-stack-1x">+@Model.Expansions.Count</strong>
                </span>
            }
        </div>
    </div>
    <div class="lot-text pt-1">
        <strong>@Html.Raw(Model.Year > 0 ? $"{Model.Name} ({Model.Year})" : Model.Name)</strong>
        <small>@Model.VersionName</small>
        @if (string.IsNullOrWhiteSpace(Model.Notes) == false)
        {
            <div class="notes"><p>@Model.Notes</p></div>
        }
    </div>
}

BoardGameAuction/Views/Shared/_Lot.cshtml
@model Lot
@using BoardGameAuction.Models.Types
@{ 
    bool isTheSeller = Model.Seller != null && User.HasClaim("role", ((int)RoleType.Seller).ToString());
    bool isAdmin = User.HasClaim(c => c.Type == "role" && c.Value == ((int)BoardGameAuction.Models.Types.RoleType.AuctionAdmin).ToString());
    bool isActiveLot = Model.Id == int.Parse(ViewData["activeLotId"]?.ToString() ?? "0");
    var lotClasses = "lot";
    if (isAdmin == false) { lotClasses += " movefirstwhenactive"; }
    if (isActiveLot) { lotClasses += " active"; }
}

    <div id="lot-wrapper-@Model.Id" class="@lotClasses">
        <input type="radio" value="lot-@Model.Id" id="lot-@Model.Id" name="activeLot" @if(isActiveLot) { @Html.Raw("checked"); }/>
        <div class="lot-card card my-1 m-md-1 p-md-2 shadow-sm @Html.Raw(isTheSeller ? "yourLot" : "")">
            <div class="lot-card-body d-flex flex-row flex-wrap">
                @if (Model.Items.Count == 1)
                {
                    @await Html.PartialAsync("_Item", Model.Items[0])
                }
                else
                {
                    int imageWidth = 190 / 2;
                    @for (int index = 0; index < Model.Items.Count; index++)
                    {
                        @if (index == 3 && Model.Items.Count > 4)
                        {
                            <div class="lot-image-overflow">@Html.Raw($"+{Model.Items.Count - 3}")</div>
                            break;
                        }
                        <a href=@Url.Action("Index", "Lot", new { id = Model.Items[0].LotId })>
                            <img class="lot-image-multi" src=@Model.Items[index].ImageUrl width=@Html.Raw(imageWidth) />
                        </a>
                    }
                    <div class="lot-text pt-1">
                        <strong>@string.Join(" + ", Model.Items.Select(x => x.Year > 0 ? $"{x.Name} ({x.Year})" : x.Name))</strong>
                        @if (Model.Items.Any(x => string.IsNullOrWhiteSpace(x.Notes) == false))
                        {
                            <div class="notes">
                                @foreach (var note in Model.Items.Where(y => string.IsNullOrWhiteSpace(y.Notes) == false))
                                {
                                    <p>
                                        <strong>@note.Name:</strong> @note.Notes
                                    </p>
                                }
                            </div>
                        }
                    </div>
                }

                @if (isAdmin)
                {
                    @await Html.PartialAsync("~/Views/Lot/_LotSell.cshtml", Model)
                }
                @Html.ValidationSummary(true)
            </div>
        </div>
    </div>

BoardGameAuction/Views/Shared/_NameSearchResult.cshtml
@model NameSearchResponse

<span asp-validation-summary="All" />
@foreach (var item in Model.Items)
{
    <button type="button" class="resultRow py-2" onclick="ajaxPartial('@Url.Action("ById", "Search", new { @id = item.BGGId })', '#searchForm', false)">@item.Name@if (item.Year != 0) { @Html.Raw($" ({item.Year})"); }</button>
}